---
- hosts: all
  tasks:
  - name: create a file on all machines
    file:
      dest: /tmp/file_02
      state: touch
    tags:
      - create-file

- hosts: all:!db
  tags: 
    - delete-file
  tasks:
  - name: delete a file from non-db
    file:
      dest: /tmp/file_02
      state: absent
    
- hosts: db2
  tasks:
  - name: delete a file from db2 only
    file:
      dest: /tmp/file_02
      state: absent
    tags:
      - delete-file    
  